import { useState } from "react";
import { Activity, ArrowLeft, Building2, CheckCircle2, LifeBuoy, MailWarning, ShieldAlert } from "lucide-react";
import { Link, Navigate } from "@/lib/router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataSurface } from "@/components/workspace/DataSurface";
import { useAuth } from "@/contexts/AuthContext";
import { usePilotOperations } from "@/hooks/usePilotOperations";
import { FounderFunnelScorecard } from "@/components/operations/FounderFunnelScorecard";

const requestStates = ["new", "contacted", "approved", "declined", "failed"];
const checklistStates = ["pending", "in_progress", "complete", "blocked", "not_applicable"];
const caseStates = ["open", "investigating", "waiting_on_team", "resolved", "closed"];

export default function PilotOperations() {
  const { user, isLoading: authLoading } = useAuth(); const ops = usePilotOperations();
  const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [email, setEmail] = useState(""); const [requestId, setRequestId] = useState(""); const [funnelPeriod, setFunnelPeriod] = useState<"last_30_days" | "last_90_days">("last_30_days");
  if (!authLoading && !user) return <Navigate to="/sign-in?next=/ops" replace />;
  if (ops.isLoading || authLoading) return <div className="workspace-shell grid min-h-screen place-items-center text-sm text-[var(--workspace-muted)]">Verifying operator access…</div>;
  if (ops.error || !ops.data) return <div className="workspace-shell grid min-h-screen place-items-center px-5"><div className="max-w-lg text-center"><ShieldAlert className="mx-auto h-8 w-8 text-amber-300" /><h1 className="mt-5 text-3xl font-semibold">Platform operator access required</h1><p className="mt-3 text-sm text-[var(--workspace-muted)]">Tenant roles do not grant cross-workspace access. Your account must be present in the active platform operator allowlist.</p><Button asChild className="mt-6"><Link to="/overview"><ArrowLeft className="h-4 w-4" />Return to workspace</Link></Button></div></div>;
  const failures = [...ops.data.invitations.filter((item) => item.delivery_status === "failed"), ...ops.data.deliveries.filter((item) => item.status === "failed")];
  return <main className="workspace-shell min-h-screen px-5 py-8 lg:px-10"><div className="mx-auto max-w-[1500px] space-y-7"><header className="flex flex-col gap-4 border-b border-[var(--workspace-rule)] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="workspace-eyebrow text-[var(--workspace-accent)]">Private · allowlisted operators</p><h1 className="mt-2 text-4xl font-semibold">Pilot operations</h1><p className="mt-2 text-sm text-[var(--workspace-muted)]">Provisioning, onboarding, delivery health and support across managed workspaces.</p></div><Button asChild variant="outline"><Link to="/overview"><ArrowLeft className="h-4 w-4" />Dashboard</Link></Button></header>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Building2,"Pilot workspaces",ops.data.tenants.length],[Activity,"Open requests",ops.data.requests.filter((item)=>!["approved","declined"].includes(item.status)).length],[MailWarning,"Delivery failures",failures.length],[LifeBuoy,"Open support",ops.data.supportCases.filter((item)=>!["resolved","closed"].includes(item.status)).length]].map(([Icon,label,value])=><DataSurface key={String(label)} className="p-5"><Icon className="h-5 w-5 text-[var(--workspace-accent)]" /><p className="mt-5 text-3xl font-semibold">{String(value)}</p><p className="mt-1 text-sm text-[var(--workspace-muted)]">{String(label)}</p></DataSurface>)}</section>
  <FounderFunnelScorecard period={funnelPeriod} onPeriodChange={setFunnelPeriod} />
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1.3fr)_minmax(22rem,.7fr)]"><div className="space-y-6"><DataSurface><div className="border-b border-[var(--workspace-rule)] p-5"><h2 className="font-semibold">Access request queue</h2></div><div className="divide-y divide-[var(--workspace-rule)]">{ops.data.requests.length ? ops.data.requests.map((item)=><div key={item.id} className="grid gap-3 p-5 md:grid-cols-[1fr_11rem]"><div><p className="font-medium">{item.team_name}</p><p className="mt-1 text-sm text-[var(--workspace-muted)]">{item.contact_name} · {item.email}</p>{item.message&&<p className="mt-2 text-sm">{item.message}</p>}</div><Select value={item.status} onValueChange={(status)=>ops.perform({ action:"update_request", id:item.id, status })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{requestStates.map((state)=><SelectItem key={state} value={state}>{state.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></div>) : <p className="p-5 text-sm text-[var(--workspace-muted)]">No access requests.</p>}</div></DataSurface>
  <DataSurface><div className="border-b border-[var(--workspace-rule)] p-5"><h2 className="font-semibold">Onboarding checklist</h2></div><div className="divide-y divide-[var(--workspace-rule)]">{ops.data.checklists.map((item)=><div key={item.id} className="grid gap-3 p-5 md:grid-cols-[1fr_11rem]"><div><p className="text-sm font-medium">{item.label}</p><p className="mt-1 font-mono text-xs text-[var(--workspace-subtle)]">{ops.data.tenants.find((tenant)=>tenant.id===item.tenant_id)?.name || item.tenant_id}</p></div><Select value={item.status} onValueChange={(status)=>ops.perform({ action:"update_checklist", id:item.id, tenant_id:item.tenant_id, status })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{checklistStates.map((state)=><SelectItem key={state} value={state}>{state.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></div>)}</div></DataSurface></div>
  <div className="space-y-6"><DataSurface className="p-5"><CheckCircle2 className="h-5 w-5 text-[var(--workspace-accent)]" /><h2 className="mt-4 font-semibold">Provision workspace</h2><p className="mt-2 text-sm text-[var(--workspace-muted)]">Creates the tenant, owner access or secure invitation, and managed onboarding checklist transactionally.</p><form className="mt-5 grid gap-4" onSubmit={(event)=>{event.preventDefault();ops.perform({action:"provision",name,slug,owner_email:email,request_id:requestId||null});}}><div><Label htmlFor="ops-name">Team name</Label><Input id="ops-name" required value={name} onChange={(event)=>setName(event.target.value)} className="mt-2" /></div><div><Label htmlFor="ops-slug">Workspace slug</Label><Input id="ops-slug" required value={slug} onChange={(event)=>setSlug(event.target.value)} className="mt-2" /></div><div><Label htmlFor="ops-email">Owner email</Label><Input id="ops-email" type="email" required value={email} onChange={(event)=>setEmail(event.target.value)} className="mt-2" /></div><div><Label htmlFor="ops-request">Request ID (optional)</Label><Input id="ops-request" value={requestId} onChange={(event)=>setRequestId(event.target.value)} className="mt-2" /></div><Button disabled={ops.isSaving}>Provision pilot</Button></form></DataSurface>
  <DataSurface><div className="border-b border-[var(--workspace-rule)] p-5"><h2 className="font-semibold">Delivery failures</h2></div>{failures.length ? <div className="divide-y divide-[var(--workspace-rule)]">{failures.slice(0,10).map((item)=><div key={item.id} className="p-4"><p className="text-sm font-medium">{"email" in item ? item.email : item.recipient_email}</p><p className="mt-1 text-xs text-destructive">{item.delivery_error || ("last_error" in item ? item.last_error : null) || "Delivery failed"}</p></div>)}</div> : <p className="p-5 text-sm text-[var(--workspace-muted)]">No unresolved delivery failures.</p>}</DataSurface>
  <DataSurface><div className="border-b border-[var(--workspace-rule)] p-5"><h2 className="font-semibold">Support cases</h2></div><div className="divide-y divide-[var(--workspace-rule)]">{ops.data.supportCases.map((item)=><div key={item.id} className="p-4"><p className="text-sm font-medium">{item.subject}</p><p className="mt-1 text-xs text-[var(--workspace-muted)]">{item.priority} priority</p><Select value={item.status} onValueChange={(status)=>ops.perform({action:"update_support",id:item.id,tenant_id:item.tenant_id,status})}><SelectTrigger className="mt-3"><SelectValue /></SelectTrigger><SelectContent>{caseStates.map((state)=><SelectItem key={state} value={state}>{state.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></div>)}</div></DataSurface></div></div></div></main>;
}
