-- Cover foreign keys used by the managed-pilot dashboard and server workflows.
create index if not exists calendar_events_scrim_id_idx on public.calendar_events(scrim_id);
create index if not exists coaching_action_events_actor_id_idx on public.coaching_action_events(actor_id);
create index if not exists coaching_action_events_tenant_id_idx on public.coaching_action_events(tenant_id);
create index if not exists coaching_actions_assignee_player_id_idx on public.coaching_actions(assignee_player_id);
create index if not exists coaching_actions_completed_by_idx on public.coaching_actions(completed_by);
create index if not exists coaching_actions_created_by_idx on public.coaching_actions(created_by);
create index if not exists coaching_actions_feedback_id_idx on public.coaching_actions(feedback_id);
create index if not exists coaching_actions_follow_up_scrim_id_idx on public.coaching_actions(follow_up_scrim_id);
create index if not exists coaching_actions_owner_user_id_idx on public.coaching_actions(owner_user_id);
create index if not exists coaching_actions_scrim_game_id_idx on public.coaching_actions(scrim_game_id);
create index if not exists coaching_actions_scrim_id_idx on public.coaching_actions(scrim_id);
create index if not exists collector_capture_sessions_game_id_idx on public.collector_capture_sessions(game_id);
create index if not exists collector_capture_sessions_tenant_id_idx on public.collector_capture_sessions(tenant_id);
create index if not exists collector_devices_created_by_idx on public.collector_devices(created_by);
create index if not exists collector_pairing_codes_created_by_idx on public.collector_pairing_codes(created_by);
create index if not exists collector_pairing_codes_redeemed_device_idx on public.collector_pairing_codes(redeemed_by_device_id);
create index if not exists collector_pairing_codes_tenant_id_idx on public.collector_pairing_codes(tenant_id);
create index if not exists integration_delivery_attempts_tenant_id_idx on public.integration_delivery_attempts(tenant_id);
create index if not exists matchup_matrix_data_our_player_id_idx on public.matchup_matrix_data(our_player_id);
create index if not exists notification_deliveries_notification_id_idx on public.notification_deliveries(notification_id);
create index if not exists notification_deliveries_recipient_user_id_idx on public.notification_deliveries(recipient_user_id);
create index if not exists notification_preferences_user_id_idx on public.notification_preferences(user_id);
create index if not exists notification_reminders_action_id_idx on public.notification_reminders(coaching_action_id);
create index if not exists notification_reminders_scrim_id_idx on public.notification_reminders(scrim_id);
create index if not exists notification_reminders_tenant_id_idx on public.notification_reminders(tenant_id);
create index if not exists operator_audit_events_operator_id_idx on public.operator_audit_events(operator_id);
create index if not exists operator_audit_events_tenant_id_idx on public.operator_audit_events(tenant_id);
create index if not exists opponent_external_drafts_team_tenant_idx on public.opponent_external_draft_games(opponent_team_id, tenant_id);
create index if not exists pilot_onboarding_items_completed_by_idx on public.pilot_onboarding_items(completed_by);
create index if not exists platform_operators_created_by_idx on public.platform_operators(created_by);
create index if not exists player_rank_history_tenant_id_idx on public.player_rank_history(tenant_id);
create index if not exists players_linked_user_id_idx on public.players(linked_user_id);
create index if not exists scouting_evidence_opponent_tenant_idx on public.scouting_evidence(opponent_team_id, tenant_id);
create index if not exists scouting_evidence_scrim_tenant_idx on public.scouting_evidence(scrim_id, tenant_id);
create index if not exists scouting_evidence_superseded_by_idx on public.scouting_evidence(superseded_by);
create index if not exists scouting_evidence_superseded_evidence_tenant_idx on public.scouting_evidence(superseded_by_evidence_id, tenant_id);
create index if not exists scouting_tendencies_opponent_tenant_idx on public.scouting_tendencies(opponent_team_id, tenant_id);
create index if not exists scouting_tendency_evidence_evidence_tenant_idx on public.scouting_tendency_evidence(evidence_id, tenant_id);
create index if not exists scouting_tendency_evidence_tenant_id_idx on public.scouting_tendency_evidence(tenant_id);
create index if not exists scouting_tendency_evidence_tendency_tenant_idx on public.scouting_tendency_evidence(tendency_id, tenant_id);
create index if not exists scrim_participants_player_tenant_idx on public.scrim_participants(player_id, tenant_id);
create index if not exists scrims_archived_by_idx on public.scrims(archived_by);
create index if not exists scrims_opponent_team_tenant_idx on public.scrims(opponent_team_id, tenant_id);
create index if not exists support_cases_assigned_operator_id_idx on public.support_cases(assigned_operator_id);
create index if not exists support_cases_opened_by_idx on public.support_cases(opened_by);
create index if not exists support_cases_tenant_id_idx on public.support_cases(tenant_id);
create index if not exists team_invitations_invited_by_idx on public.team_invitations(invited_by);
create index if not exists team_invitations_player_tenant_idx on public.team_invitations(player_id, tenant_id);
create index if not exists tenant_riot_integrations_created_by_idx on public.tenant_riot_integrations(created_by);
create index if not exists tenant_riot_integrations_updated_by_idx on public.tenant_riot_integrations(updated_by);
create index if not exists tenant_users_invited_by_idx on public.tenant_users(invited_by);
create index if not exists tenant_users_user_id_idx on public.tenant_users(user_id);
